# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' auxiliary function that does weighted Tempered Gibbs Sampling from the posterior distribution of Gamma
#'
#' Performs weighted Tempered Gibbs Sampling 
#'
#' @param X_ a matrix of p regressors (independent variables) with dimension (nxp).
#' @param y_ a vector of n observations (dependent variable) with dimensions (nx1).
#' @param n_ number of observations n.
#' @param p_ number of regressors p.
#' @param n_iter a positive integer specifying the number of iterations for the Markov Chain.
#' @param burnin_ a positive integer specifying the number of burn in iterations for the Markov Chain.
#' @param h1_ first parameter of the beta distribution defining h. If value of h fixed, make it h1.
#' @param h2_ second parameter of the beta distribution defining h. If value of h fixed, make h2=0.
#' @param c_ constant of proportionality to prior covariace matrix.
#' @param k_ k_weighted parameter for weighted sampling.
#' @param weighted boolean indicating if weighted sampling.
#'
#' @return List with values for PIP and required elements to reproduce the samples. 
wTGS <- function(X_, y_, n_, p_, n_iter, burnin_, h1_, h2_, c_, k_, weighted) {
    .Call(`_scaleBVS_wTGS`, X_, y_, n_, p_, n_iter, burnin_, h1_, h2_, c_, k_, weighted)
}

